% Open this file in the GNU Octave GUI and press F5.
project_folder = fileparts(mfilename('fullpath'));

% -----------------------------
% Create custom launcher window
% -----------------------------
screen_size = get(0, 'screensize');
dlg_w = 720;
dlg_h = 430;
dlg_x = max(50, round((screen_size(3) - dlg_w) / 2));
dlg_y = max(50, round((screen_size(4) - dlg_h) / 2));

f = figure( ...
    'Name', 'QKD over FSO | Project Launcher', ...
    'NumberTitle', 'off', ...
    'MenuBar', 'none', ...
    'ToolBar', 'none', ...
    'Resize', 'off', ...
    'WindowStyle', 'modal', ...
    'Color', [0.94 0.97 1.00], ...
    'Position', [dlg_x dlg_y dlg_w dlg_h], ...
    'CloseRequestFcn', 'setappdata(gcbf,''scenario'',0); uiresume(gcbf);' ...
);

setappdata(f, 'scenario', 0);

% -----------------------------
% Header
% -----------------------------
uicontrol(f, ...
    'Style', 'text', ...
    'String', 'QKD over FSO Simulation Project', ...
    'Units', 'normalized', ...
    'Position', [0.07 0.86 0.86 0.09], ...
    'BackgroundColor', [0.94 0.97 1.00], ...
    'ForegroundColor', [0.10 0.20 0.45], ...
    'FontSize', 18, ...
    'FontWeight', 'bold', ...
    'HorizontalAlignment', 'center');

uicontrol(f, ...
    'Style', 'text', ...
    'String', 'Choose a project scenario to launch', ...
    'Units', 'normalized', ...
    'Position', [0.12 0.79 0.76 0.05], ...
    'BackgroundColor', [0.94 0.97 1.00], ...
    'ForegroundColor', [0.25 0.25 0.25], ...
    'FontSize', 11, ...
    'HorizontalAlignment', 'center');

% -----------------------------
% Button style settings
% -----------------------------
btn_color = [0.18 0.42 0.75];
btn_text_color = [1 1 1];
btn_w = 0.72;
btn_h = 0.10;
btn_x = 0.14;

% -----------------------------
% Scenario buttons
% -----------------------------
uicontrol(f, ...
    'Style', 'pushbutton', ...
    'String', '1  -  Basic LOS FSO', ...
    'Units', 'normalized', ...
    'Position', [btn_x 0.63 btn_w btn_h], ...
    'FontSize', 12, ...
    'FontWeight', 'bold', ...
    'BackgroundColor', btn_color, ...
    'ForegroundColor', btn_text_color, ...
    'Callback', 'setappdata(gcbf,''scenario'',1); uiresume(gcbf);');

uicontrol(f, ...
    'Style', 'pushbutton', ...
    'String', '2  -  Ground Station and Satellite', ...
    'Units', 'normalized', ...
    'Position', [btn_x 0.50 btn_w btn_h], ...
    'FontSize', 12, ...
    'FontWeight', 'bold', ...
    'BackgroundColor', btn_color, ...
    'ForegroundColor', btn_text_color, ...
    'Callback', 'setappdata(gcbf,''scenario'',2); uiresume(gcbf);');

uicontrol(f, ...
    'Style', 'pushbutton', ...
    'String', '3  -  Two Ground and One Satellite', ...
    'Units', 'normalized', ...
    'Position', [btn_x 0.37 btn_w btn_h], ...
    'FontSize', 12, ...
    'FontWeight', 'bold', ...
    'BackgroundColor', btn_color, ...
    'ForegroundColor', btn_text_color, ...
    'Callback', 'setappdata(gcbf,''scenario'',3); uiresume(gcbf);');

uicontrol(f, ...
    'Style', 'pushbutton', ...
    'String', '4  -  Two Ground and Two or More Satellites as Nodes', ...
    'Units', 'normalized', ...
    'Position', [btn_x 0.24 btn_w btn_h], ...
    'FontSize', 11, ...
    'FontWeight', 'bold', ...
    'BackgroundColor', btn_color, ...
    'ForegroundColor', btn_text_color, ...
    'Callback', 'setappdata(gcbf,''scenario'',4); uiresume(gcbf);');

% -----------------------------
% Footer note
% -----------------------------
uicontrol(f, ...
    'Style', 'text', ...
    'String', 'Each option opens the corresponding START_HERE.m file', ...
    'Units', 'normalized', ...
    'Position', [0.15 0.12 0.70 0.04], ...
    'BackgroundColor', [0.94 0.97 1.00], ...
    'ForegroundColor', [0.35 0.35 0.35], ...
    'FontSize', 10, ...
    'HorizontalAlignment', 'center');

% Cancel button
uicontrol(f, ...
    'Style', 'pushbutton', ...
    'String', 'Cancel', ...
    'Units', 'normalized', ...
    'Position', [0.40 0.04 0.20 0.06], ...
    'FontSize', 11, ...
    'BackgroundColor', [0.85 0.85 0.85], ...
    'Callback', 'setappdata(gcbf,''scenario'',0); uiresume(gcbf);');

% Wait for selection
uiwait(f);

if ishandle(f)
    scenario = getappdata(f, 'scenario');
    delete(f);
else
    scenario = 0;
end

% -----------------------------
% Launch selected scenario
% -----------------------------
switch scenario
    case 1
        run(fullfile(project_folder, '1-Basic LOS FSO', 'START_HERE.m'));
    case 2
        run(fullfile(project_folder, '2-Ground Station and Satellite', 'START_HERE.m'));
    case 3
        run(fullfile(project_folder, '3-Two Ground and One Satellite', 'START_HERE.m'));
    case 4
        run(fullfile(project_folder, '4-Two Ground and Multiple Satellites', 'START_HERE.m'));
    otherwise
        disp('No scenario selected.');
endswitch
