function value = leo_summary_text(R)
  P=R.parameters; E=R.example;
  value=sprintf(['LEO SATELLITE FSO / EXTENSION STAGE\n', ...
    'Ideal circular overhead downlink; static spherical Earth.\n\n', ...
    'Altitude: %.0f km | Minimum elevation: %.1f degrees\n', ...
    'Contact duration: %.3f s (%.3f min)\n', ...
    'Slant range: %.3f to %.3f km\n', ...
    'Pulse clock: %.4g Hz | Signal allocation: %.3f\n', ...
    'Expected signal-slot detections over pass: %.3f\n', ...
    'Expected sifted bits over pass: %.3f\n', ...
    'Detection-weighted pass QBER: %.4f%%\n', ...
    'Peak ideal decoy model rate: %.3f bits/s\n', ...
    'Integrated asymptotic model bits: %.3f\n\n', ...
    'EXAMPLE FED TO EXISTING BIT PROCESSING\n', ...
    'Elevation: %.1f degrees | Slant range: %.3f km\n', ...
    'Atmospheric path: %.3f km (not the full satellite range)\n', ...
    'Total detection-path efficiency: %.8g | Baseline QBER: %.4f%%\n'], ...
    P.altitude_km,P.min_elevation_deg,R.pass_duration_s,R.pass_duration_s/60, ...
    min(R.pass.slant_range_km),max(R.pass.slant_range_km), ...
    P.pulse_rate_hz,P.signal_duty_fraction,R.expected_detections, ...
    R.expected_sifted_bits,100*R.pooled_qber,max(R.pass.key_rate_bps), ...
    R.integrated_key_bits,P.example_elevation_deg,E.slant_range_km, ...
    E.atmosphere_path_km,E.eta,100*E.qber_bb84);
  if ~isempty(R.postprocessing)
    B=R.postprocessing;
    value=[value,sprintf(['Detected inputs in separate example: %d | Eve interception: %.3f\n', ...
      'Sifted bits: %d | Observed QBER: %.4f%%\n', ...
      'Errors before / after LDPC: %d / %d | Iterations: %d\n', ...
      'Teaching hash output: %d bits | Matching outputs: %d\n'], ...
      B.parameters.n_signals,B.parameters.eve_intercept_fraction,B.n_key,100*B.observed_qber, ...
      sum(B.eve.alice_key~=B.eve.bob_key),sum(B.eve.alice_key~=B.bob_corrected), ...
      B.iterations,B.final_bits,B.final_key_match)];
    if ~isempty(B.abort_reason), value=[value,'No-output reason: ',B.abort_reason,sprintf('\n')]; end
  else
    value=[value,'Bit example skipped: no available detections.',sprintf('\n')];
  end
  value=[value,sprintf(['\nThe pass integral is an ideal asymptotic benchmark, not a finite-key\n', ...
    'secure length. The separate detected-signal bit example uses one\n', ...
    'elevation; its output count is not the number of keys from the pass.\n', ...
    'Atmosphere: effective homogeneous shell; pointing: fixed loss.\n', ...
    'No weather outages, time-dependent turbulence, orbital tracking or\n', ...
    'finite-decoy parameter estimation are simulated.\n'])];
end
