function P=extension_ui_defaults(P,stage)
  % Numerical storage keeps the existing parameter/export formats compatible.
  values=struct('x_protocol',1,'x_fading_mode',1,'x_sigma',.3,'x_tau_s',2, ...
    'x_seed',123,'x_visibility',.98,'x_mean_photons',.1,'x_background',1e-6, ...
    'x_phase_rad',0,'x_clock_hz',1e8,'x_duty',.8,'x_train_pulses',1024, ...
    'x_guard_slots',1,'x_ec',1.16,'x_realizations',5,'x_link_b_protocol',1, ...
    'extension_samples',5000,'extension_dt_s',.02);
  names=fieldnames(values);
  for k=1:numel(names), if ~isfield(P,names{k}), P.(names{k})=values.(names{k}); end; end
end
