function groups=extension_ui_groups(stage)
  groups={make('Protocol and turbulence', ...
    'These settings update the protocol/fading pages in this same window. DPS rates are proxies.', ...
    {'x_protocol','x_fading_mode','x_sigma','x_tau_s','x_seed','x_realizations'}, ...
    {'Link protocol','Atmospheric fading','Log-irradiance sigma','Correlation time (s)','Fading random seed','Independent realizations'}), ...
    make('DPS source and detectors','DPS-only inputs; original BB84 bit processing keeps its own settings.', ...
    {'x_mean_photons','x_visibility','x_background','x_phase_rad','x_ec'}, ...
    {'Mean photons / pulse','Visibility (0-1)','Background / detector / gate','Phase offset (rad)','Error correction factor'}), ...
    make('DPS timing','Pulse clock and guard slots determine the rate in bits per second.', ...
    {'x_clock_hz','x_duty','x_train_pulses','x_guard_slots'}, ...
    {'DPS clock (Hz)','DPS active duty (0-1)','Pulses / coherent train','Empty guard slots'})};
  if stage==1
    groups{3}.fields=[groups{3}.fields,{'extension_samples','extension_dt_s'}];
    groups{3}.labels=[groups{3}.labels,{'Temporal sample count','Temporal sample interval (s)'}];
  end
  if stage==3
    groups{1}.fields{end+1}='x_link_b_protocol'; groups{1}.labels{end+1}='Ground B link protocol';
    groups{1}.hint='Trusted links use the selected protocols. The existing architecture selector retains separate BBM92 operation.';
  end
end
function G=make(name,hint,fields,labels)
  G=struct('name',name,'hint',hint,'fields',{fields},'labels',{labels});
end
