function value = network_summary_text(R)
  P = R.parameters; M = R.metrics;
  route = R.route_nodes{R.best_index};
  if isempty(route), route_name = 'No connected route';
  else, route_name = strjoin(R.node_names(route),' -> '); end
  value = sprintf(['Scenario %d: two ground stations and %d satellite node(s)\n', ...
    'Ground separation: %.1f km | altitude: %.1f km\n', ...
    'Observation window: %.1f s | samples: %d\n', ...
    'Peak simultaneous route rate: %.6f kbit/s\n', ...
    'Integrated simultaneous-route model bits: %.6f Mbit\n', ...
    'Sampled connected duration (trapezoidal): %.3f s\n', ...
    'Peak route at t = %.1f s: %s\n'], ...
    P.stage,P.satellite_count,P.ground_separation_km,P.link.altitude_km, ...
    P.duration_s,P.time_points,M.peak_rate_bps/1000,M.integrated_key_bits/1e6, ...
    M.connected_duration_s,R.time_s(R.best_index),route_name);
  if P.stage == 3
    value = [value,sprintf('Post-window stored pair-key budget: %.6f Mbit\n',M.stored_pair_bits/1e6)];
  end
  if isfield(R,'comparison')
    C=R.comparison;
    value=[value,sprintf(['\nSelected architecture: %s\n', ...
      'Selected expected/asymptotic bits: %.9f\n', ...
      'Trusted two-pool causal delivered budget: %.9f bits\n', ...
      'BBM92 common visibility: %.3f s\nBBM92 peak asymptotic rate: %.9f bit/s\n', ...
      'BBM92 integrated asymptotic estimate: %.9f bits\n', ...
      'BBM92: no satellite key assigned; trusted receiver and symmetric-basis assumptions.\n'], ...
      C.architecture,C.selected_key_bits,C.trusted.delivered_bits,C.bbm92.metrics.common_visibility_s, ...
      C.bbm92.metrics.peak_key_rate_bps,C.bbm92.metrics.integrated_key_bits)];
    if isfield(C.bbm92,'available') && ~C.bbm92.available
      value=[value,sprintf('BBM92 unavailable (NaN estimates): %s\n',C.bbm92.reason)];
    end
  end
  if isfield(R,'demonstration')
    value = [value,sprintf('\nSeparate BB84 / LDPC / hash / trusted relay example:\n%s\n',R.demonstration.status)];
    for h = 1:numel(R.demonstration.hops)
      B = R.demonstration.hops{h}; edge = R.edges(R.demonstration.edge_indices(h));
      value = [value,sprintf('%s: baseline QBER %.3f%%, observed with Eve %.3f%%, sifted %d, errors after LDPC %d, output %d bits\n', ...
        edge.label,100*B.channel_qber,100*B.observed_qber,B.n_key, ...
        sum(B.eve.alice_key ~= B.bob_corrected),B.final_bits)];
    end
  end
  value = [value,sprintf(['\nTrusted Mode A / Stage 4 baseline: classical relays, independent QKD per edge.\n', ...
    'Route capacity is the minimum hop rate; choose one widest route per sample.\n', ...
    'Independent simultaneous terminals and pulse budgets are assumed per edge.\n', ...
    'No shared-terminal scheduling, finite-key proof, weather or Earth rotation.\n', ...
    'No quantum repeaters, entanglement swapping, or multi-route key storage model.\n', ...
    'The seeded bit example and asymptotic integrated rates are distinct.\n'])];
end
