function text_out = qkd_summary_text(R)
  % One readable summary shared by the console and exported report.
  P = R.parameters;
  if P.use_fso_qber
    mode = 'FSO-derived BB84 QBER at the example distance';
  else
    mode = 'Manual channel QBER (same separation as the Python notebook)';
  end
  text_out = sprintf([ ...
    'QKD OVER FSO - OCTAVE RESULTS\n' ...
    '============================================================\n' ...
    '1. OPTICAL LINK (baseline without Eve)\n' ...
    'Example distance                    : %.2f km\n' ...
    'Selected atmospheric loss           : %.3f dB/km\n' ...
    'Total detection-path efficiency     : %.8g\n' ...
    'Detection gain per pulse            : %.8g\n' ...
    'BB84 model QBER                     : %.4f %%\n' ...
    'BB84 reference rate / pulse         : %.8g\n' ...
    'Decoy-BB84 model rate / pulse        : %.8g\n' ...
    'Legacy DPS teaching proxy / pulse          : %.8g\n\n' ...
    '2. FADING EXAMPLE\n' ...
    'Mean instantaneous QBER             : %.4f %%\n' ...
    '95th percentile instantaneous QBER  : %.4f %%\n\n' ...
    '3. EVE AND BASIS SIFTING\n' ...
    'Channel setting mode                : %s\n' ...
    'Actual pre-Eve channel QBER          : %.4f %%\n' ...
    'Eve interception                    : %.2f %%\n' ...
    'Detected signals before sifting     : %d\n' ...
    'Sifted bits                         : %d\n' ...
    'Expected / observed total QBER      : %.4f %% / %.4f %%\n' ...
    'Errors before reconciliation        : %d\n' ...
    'Eve-known bits BEFORE syndrome      : %d\n\n' ...
    '4. LDPC INFORMATION RECONCILIATION\n' ...
    'Parity checks / graph edges         : %d / %d\n' ...
    'Converged / iterations              : %d / %d\n' ...
    'Exact corrected-key match           : %d\n' ...
    'QBER after reconciliation           : %.4f %%\n' ...
    'Public syndrome leakage estimate    : %d bits\n' ...
    'Measured f_EC (NaN if undefined)     : %.5g\n\n' ...
    '5. TOEPLITZ HASH DEMONSTRATION\n' ...
    'Illustrative available budget       : %d bits\n' ...
    'Requested / produced output         : %d / %d bits\n'], ...
    P.demo_distance_km,P.atmospheric_loss_db_km,R.example.eta,R.example.gain, ...
    100*R.example.qber_bb84,R.example.rate_bb84,R.example.rate_decoy,R.example.rate_dps, ...
    100*R.turbulence.mean_qber,100*R.turbulence.p95_qber,mode,100*R.channel_qber, ...
    100*P.eve_intercept_fraction,P.n_signals,R.n_key,100*R.eve.expected_qber, ...
    100*R.observed_qber,sum(R.eve.alice_key ~= R.eve.bob_key),R.eve_known_bits, ...
    R.m_checks,nnz(R.H),R.converged,R.iterations,R.reconciliation_ok,100*R.qber_after, ...
    R.leak_ec,R.f_ec,R.demo_key_budget,P.requested_final_bits,R.final_bits);
  if R.final_bits > 0
    text_out = [text_out, sprintf('Final keys identical                : %d\n',R.final_key_match)];
    text_out = [text_out, sprintf('First output bits (up to 64)         : %s\n', ...
                        sprintf('%d',R.alice_final(1:min(64,R.final_bits))))];
  else
    text_out = [text_out, sprintf('NO FINAL KEY: %s\n',R.abort_reason)];
  end
  text_out = [text_out, sprintf([ ...
    '\nThis is a reproducible teaching simulation. The DPS rate is a proxy.\n' ...
    'The fixed privacy reserve is illustrative, not a finite-key proof.\n' ...
    'Agreement demonstrates correctness; it does not certify secrecy.\n'])];
end
